#!/usr/bin/env bash
# Build Witzper.app bundle so macOS can grant it Accessibility permission
# as a distinct app (not "Terminal" or the raw binary).
set -euo pipefail
cd "$(dirname "$0")/.."

APP_NAME="Witzper"
APP_DIR="build/${APP_NAME}.app"
CONTENTS="${APP_DIR}/Contents"
MACOS="${CONTENTS}/MacOS"
RES="${CONTENTS}/Resources"

# Version is read from the VERSION file at the repo root — the single source
# of truth consumed by build_app.sh, scripts/release.sh, and the in-app
# Updater (which compares it against GitHub Releases). Bump by running
# scripts/release.sh X.Y.Z, not by hand-editing this file.
VERSION="$(cat VERSION | tr -d '[:space:]')"
if [[ -z "$VERSION" ]]; then
    echo "ERROR: VERSION file is empty" >&2
    exit 1
fi
# CFBundleVersion is a monotonic build number. We use the number of git
# commits reachable from HEAD so it strictly increases even between tagged
# releases. Falls back to "1" outside a git checkout.
BUILD_NUMBER="$(git rev-list --count HEAD 2>/dev/null || echo 1)"

echo "→ building Swift helper (release)"
(cd swift-helper && swift build -c release)

echo "→ assembling ${APP_DIR}"
rm -rf "${APP_DIR}"
mkdir -p "${MACOS}" "${RES}"

cp swift-helper/.build/release/flow-helper "${MACOS}/Witzper"
chmod +x "${MACOS}/Witzper"

cat > "${CONTENTS}/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleExecutable</key><string>Witzper</string>
    <key>CFBundleIdentifier</key><string>ai.witzper.app</string>
    <key>CFBundleName</key><string>Witzper</string>
    <key>CFBundleDisplayName</key><string>Witzper</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>${VERSION}</string>
    <key>CFBundleVersion</key><string>${BUILD_NUMBER}</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHumanReadableCopyright</key><string>Copyright © 2026 Isaac Horowitz. MIT license.</string>
    <key>NSMicrophoneUsageDescription</key><string>Witzper transcribes your voice entirely on this device.</string>
    <key>NSAppleEventsUsageDescription</key><string>Witzper reads the focused app and inserts text.</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
</dict>
</plist>
PLIST

# Copy app icon (generated by scripts/build_icon.py)
if [[ -f assets/AppIcon.icns ]]; then
    cp assets/AppIcon.icns "${RES}/AppIcon.icns"
else
    echo "⚠ assets/AppIcon.icns missing — run scripts/build_icon.py to generate it"
fi

# ----------------------------------------------------------------------------
# Bundle the Python daemon inside Contents/Resources/
# ----------------------------------------------------------------------------
# We embed a fully self-contained CPython (via uv's python-build-standalone)
# plus all of flow's dependencies so end-users don't need to clone the repo,
# install Python, or run `uv sync`. On first launch, the Swift helper spawns
# the bundled interpreter directly.
#
# Source layout inside the bundle:
#   Contents/Resources/python/             — relocatable venv (python+deps)
#   Contents/Resources/flow/               — flow package source (live)
#   Contents/Resources/configs/            — default TOML + app rules
#
# Skipped when WITZPER_SKIP_PYTHON_BUNDLE=1 (dev builds iterating on Swift
# only, where the ~4 GB venv build dominates wall time).
if [[ "${WITZPER_SKIP_PYTHON_BUNDLE:-0}" != "1" ]]; then
    if ! command -v uv >/dev/null 2>&1; then
        echo "ERROR: uv is required to bundle the Python daemon." >&2
        echo "       install: curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
        echo "       or skip:  WITZPER_SKIP_PYTHON_BUNDLE=1 $0" >&2
        exit 1
    fi

    PY_ROOT="${RES}/python"
    echo "→ bundling Python runtime into ${PY_ROOT}"
    rm -rf "${PY_ROOT}"

    # Strategy: skip `uv venv` entirely. It creates a venv whose bin/python
    # is a symlink to uv's managed CPython install at a build-machine-
    # specific absolute path (e.g. /Users/runner/.local/share/uv/...).
    # --relocatable only relocates the venv's own shims; the symlink out
    # of the venv stays absolute, so the bundled python is dead on any
    # machine that isn't the build machine.
    #
    # Instead, copy uv's managed python-build-standalone tree *as-is* into
    # the bundle. python-build-standalone is explicitly designed for
    # embedding — sys.prefix is computed from the binary's own location,
    # all dylib paths are @executable_path-relative. We then use its own
    # pip to install flow + deps into its site-packages, so there's no
    # venv indirection at all.

    # 1. Make sure uv has managed CPython 3.13 available.
    uv python install 3.13 --python-preference only-managed >/dev/null
    UV_PY="$(uv python find 3.13 --managed-python)"
    if [[ -z "$UV_PY" || ! -x "$UV_PY" ]]; then
        echo "ERROR: could not locate uv-managed CPython 3.13" >&2
        exit 1
    fi
    # UV_PY = .../cpython-3.13-macos-aarch64-none/bin/python3.13
    # Install root is two levels up.
    UV_PY_ROOT="$(dirname "$(dirname "$UV_PY")")"

    # 2. Copy the whole install tree into the bundle, dereferencing any
    #    outer symlinks so the result is fully self-contained.
    echo "  copying ${UV_PY_ROOT} → ${PY_ROOT}"
    mkdir -p "$(dirname "${PY_ROOT}")"
    cp -RL "${UV_PY_ROOT}" "${PY_ROOT}"

    # uv's managed CPython ships a PEP 668 marker that pip refuses to
    # touch ("This environment is externally managed"). That's correct
    # for uv's *canonical* install, but we've copied the tree into our
    # own bundle — it's no longer managed by uv, so the marker must go.
    find "${PY_ROOT}" -name "EXTERNALLY-MANAGED" -delete 2>/dev/null || true

    # 3. Install flow + runtime deps into the bundled python's site-
    #    packages directly. No venv. We use pip via `python -m pip` against
    #    the bundled interpreter itself — it's already ensurepip-enabled.
    echo "→ installing flow + dependencies into bundled python"
    "${PY_ROOT}/bin/python3.13" -m ensurepip --upgrade >/dev/null 2>&1 || true
    "${PY_ROOT}/bin/python3.13" -m pip install --upgrade --quiet pip
    "${PY_ROOT}/bin/python3.13" -m pip install --no-cache-dir --quiet .

    # 4. Provide friendly python / python3 symlinks inside bin/ so the
    #    helper's spawn script can call "python" without version suffixing.
    #    These are relative symlinks, so the bundle stays relocatable.
    (cd "${PY_ROOT}/bin" && ln -sf python3.13 python3 && ln -sf python3.13 python)

    echo "→ copying flow source and configs into Resources"
    rm -rf "${RES}/flow" "${RES}/configs"
    cp -R flow "${RES}/flow"
    cp -R configs "${RES}/configs"

    # Strip obvious dead weight from the bundled runtime to keep the zip
    # download reasonable. MLX still dominates at ~150 MB but every MB helps.
    find "${PY_ROOT}" -type d -name "__pycache__" -prune -exec rm -rf {} + 2>/dev/null || true
    find "${PY_ROOT}" -type d -name "tests" -prune -exec rm -rf {} + 2>/dev/null || true
    find "${PY_ROOT}" -type f -name "*.pyc" -delete 2>/dev/null || true

    # Sanity check: the bundled python must not contain any absolute
    # references to the build machine's paths, otherwise the whole
    # relocation story falls apart.
    BUILD_HOME_LEAK="$(grep -r -l "/Users/runner\\|/opt/homebrew/Cellar" "${PY_ROOT}/bin" 2>/dev/null || true)"
    if [[ -n "$BUILD_HOME_LEAK" ]]; then
        echo "  WARNING: bundled python bin/ leaks build-machine paths:" >&2
        echo "  $BUILD_HOME_LEAK" >&2
    fi

    PY_SIZE="$(du -sh "${PY_ROOT}" 2>/dev/null | awk '{print $1}')"
    echo "  bundled python: ${PY_SIZE}"
else
    echo "→ skipping python bundle (WITZPER_SKIP_PYTHON_BUNDLE=1)"
fi

# Ad-hoc sign so it runs without Gatekeeper friction. --deep recursively
# signs every embedded binary in Contents/Resources/python (python3, each
# .dylib, each .so). Without this, the first-launch spawn of the bundled
# interpreter would be killed by macOS with a code-signing violation.
codesign --force --deep --sign - "${APP_DIR}" 2>/dev/null || true

echo "✔ built ${APP_DIR} (v${VERSION} build ${BUILD_NUMBER})"
echo "  install: cp -r ${APP_DIR} /Applications/"
echo "  run:     open ${APP_DIR}"
