#!/usr/bin/env bash
# Build Witzper.app bundle so macOS can grant it Accessibility permission
# as a distinct app (not "Terminal" or the raw binary).
set -euo pipefail
cd "$(dirname "$0")/.."

APP_NAME="Witzper"
APP_DIR="build/${APP_NAME}.app"
CONTENTS="${APP_DIR}/Contents"
MACOS="${CONTENTS}/MacOS"
RES="${CONTENTS}/Resources"

# Version is read from the VERSION file at the repo root — the single source
# of truth consumed by build_app.sh, scripts/release.sh, and the in-app
# Updater (which compares it against GitHub Releases). Bump by running
# scripts/release.sh X.Y.Z, not by hand-editing this file.
VERSION="$(cat VERSION | tr -d '[:space:]')"
if [[ -z "$VERSION" ]]; then
    echo "ERROR: VERSION file is empty" >&2
    exit 1
fi
# CFBundleVersion is a monotonic build number. We use the number of git
# commits reachable from HEAD so it strictly increases even between tagged
# releases. Falls back to "1" outside a git checkout.
BUILD_NUMBER="$(git rev-list --count HEAD 2>/dev/null || echo 1)"

echo "→ building Swift helper (release)"
(cd swift-helper && swift build -c release)

echo "→ assembling ${APP_DIR}"
rm -rf "${APP_DIR}"
mkdir -p "${MACOS}" "${RES}"

cp swift-helper/.build/release/flow-helper "${MACOS}/Witzper"
chmod +x "${MACOS}/Witzper"

cat > "${CONTENTS}/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key><string>en</string>
    <key>CFBundleExecutable</key><string>Witzper</string>
    <key>CFBundleIdentifier</key><string>ai.witzper.app</string>
    <key>CFBundleName</key><string>Witzper</string>
    <key>CFBundleDisplayName</key><string>Witzper</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>${VERSION}</string>
    <key>CFBundleVersion</key><string>${BUILD_NUMBER}</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHumanReadableCopyright</key><string>Copyright © 2026 Isaac Horowitz. MIT license.</string>
    <key>NSMicrophoneUsageDescription</key><string>Witzper transcribes your voice entirely on this device.</string>
    <key>NSAppleEventsUsageDescription</key><string>Witzper reads the focused app and inserts text.</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
</dict>
</plist>
PLIST

# Copy app icon (generated by scripts/build_icon.py)
if [[ -f assets/AppIcon.icns ]]; then
    cp assets/AppIcon.icns "${RES}/AppIcon.icns"
else
    echo "⚠ assets/AppIcon.icns missing — run scripts/build_icon.py to generate it"
fi

# ----------------------------------------------------------------------------
# Bundle the Python daemon inside Contents/Resources/
# ----------------------------------------------------------------------------
# We embed a fully self-contained CPython (via uv's python-build-standalone)
# plus all of flow's dependencies so end-users don't need to clone the repo,
# install Python, or run `uv sync`. On first launch, the Swift helper spawns
# the bundled interpreter directly.
#
# Source layout inside the bundle:
#   Contents/Resources/python/             — relocatable venv (python+deps)
#   Contents/Resources/flow/               — flow package source (live)
#   Contents/Resources/configs/            — default TOML + app rules
#
# Skipped when WITZPER_SKIP_PYTHON_BUNDLE=1 (dev builds iterating on Swift
# only, where the ~4 GB venv build dominates wall time).
if [[ "${WITZPER_SKIP_PYTHON_BUNDLE:-0}" != "1" ]]; then
    if ! command -v uv >/dev/null 2>&1; then
        echo "ERROR: uv is required to bundle the Python daemon." >&2
        echo "       install: curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
        echo "       or skip:  WITZPER_SKIP_PYTHON_BUNDLE=1 $0" >&2
        exit 1
    fi

    PY_ROOT="${RES}/python"
    echo "→ bundling Python runtime into ${PY_ROOT}"
    rm -rf "${PY_ROOT}"

    # Create a relocatable venv backed by uv's managed python-build-standalone
    # interpreter. --relocatable rewrites the venv's scripts to resolve
    # sys.prefix at runtime instead of hardcoding the build-time path, so the
    # venv keeps working after the .app is dragged into /Applications.
    uv venv \
        --python 3.13 \
        --python-preference only-managed \
        --relocatable \
        "${PY_ROOT}"

    # Install flow + all runtime deps into the bundled venv. We install the
    # package (`.`) rather than just its deps so `python -m flow` resolves,
    # but at launch we prepend Contents/Resources to PYTHONPATH so the live
    # source under Resources/flow/ shadows the installed copy — this means
    # the configs/ sibling that flow.config expects via __file__/../configs
    # resolves correctly.
    uv pip install \
        --python "${PY_ROOT}/bin/python" \
        --no-cache \
        .

    echo "→ copying flow source and configs into Resources"
    rm -rf "${RES}/flow" "${RES}/configs"
    cp -R flow "${RES}/flow"
    cp -R configs "${RES}/configs"

    # Strip obvious dead weight from the bundled venv to keep the zip/dmg
    # download reasonable. MLX + torch still dominate, but every MB helps.
    find "${PY_ROOT}" -type d -name "__pycache__" -prune -exec rm -rf {} + 2>/dev/null || true
    find "${PY_ROOT}" -type d -name "tests" -prune -exec rm -rf {} + 2>/dev/null || true
    find "${PY_ROOT}" -type f -name "*.pyc" -delete 2>/dev/null || true

    PY_SIZE="$(du -sh "${PY_ROOT}" 2>/dev/null | awk '{print $1}')"
    echo "  bundled python: ${PY_SIZE}"
else
    echo "→ skipping python bundle (WITZPER_SKIP_PYTHON_BUNDLE=1)"
fi

# Ad-hoc sign so it runs without Gatekeeper friction. --deep recursively
# signs every embedded binary in Contents/Resources/python (python3, each
# .dylib, each .so). Without this, the first-launch spawn of the bundled
# interpreter would be killed by macOS with a code-signing violation.
codesign --force --deep --sign - "${APP_DIR}" 2>/dev/null || true

echo "✔ built ${APP_DIR} (v${VERSION} build ${BUILD_NUMBER})"
echo "  install: cp -r ${APP_DIR} /Applications/"
echo "  run:     open ${APP_DIR}"
